services:
  postgres:
    image: postgres:15
    container_name: sovereign_pg
    environment:
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
      POSTGRES_DB: sovereign_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata2:
